apiVersion: v1
kind: Namespace
metadata:
  name: amitk8s1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amit-deploy
  name: amit-deploy
  namespace: amitk8s1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amit-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amit-deploy
    spec:
      containers:
      - image: docker.io/ubuntu:latest
        name: kubernetestraining
        command:
        - "sleep"
        - "10000"
        ports:
        - containerPort: 80
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-deploy
  name: amitsvc1
  namespace: amitk8s1
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: amit-deploy
status:
  loadBalancer: {}

---