apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZUk1bDJXbXdrbUF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1USXdOREl6TlRaYUZ3MHpOREEwTVRBd05ESTROVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPT3BOM1p6dVFoV1A2TXRjNWtSaUVCTlIycU1YTTB3TnpUQmsrMGhQTXU2a3JnOEdMaFlEdjhvemYKaTcyYVdWQzZXeU5EOW5iVFhFRmVydHZFR0k5bmFKZUZjclZVT2g3djdpTjZKRU5yaC9USGZ0OFVZVFJSNFlOUQpMVXU1RFRNS21zaWM4OUhoK0Z5TzRMU3FuckFEeVpmTmFXa0tHK3U0OGU2WkM1elR6L0tCUjQ3aW9VYUdRMkhmClovTXNlTldlaGpaZG50MElTam9QL1lYZFpnVHN5VE0wZ0c1Mjl0Uk5NNjZYUWFzYit0eWlsZWdsbnBNVWZIUUkKaHRMaXRrNzJuR0ZDZGtOdER3a2h0MGExUHJxcXBSSmVyS1pUamxqYmlSQWJMM1BFMmZwZGdwazR6d29SMnpPbAptc2kvNytwbUpEc3pRZmk2RmZRTi9BdnlCNERkQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRTUwzaHdReThLNjJSK2ZBVTVFSVRpYzIvSTRUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2p2Mmx0bG9aVApUdUFvNEtqZkkwSzZQWjRXTGlPSnRoQ3k4V3NIS0hhbTd1ZENJRDRHeXFNVlhsbW53MCtJc2t3VjFNYkZubzRRCjMrckVYR2MwZzM5bHJDUmJNekc5Ync0TDNiR1YwRVJqMGs2djZHQ2wrODNaemlVc2I2SGVrSXNqcFF1elpKUnYKUkU4R2UzL2d2VzBJYzdCRXkxMm5mQk84YW1WcVV3b2FFOWh5b1ByTFA5QlN3Q0lkZHowSC9DSUVJOXNYdVhSaAoxUjBFdkxzbGw4N21OTGhmMlBlYnIwRW1EYm5INS9GSkZHNkI1NzNzWkd3VW9aU0pIMGZybkV3SG9lV3oxRGdTCmxQQWcycVhxSENmbE9TTURGcVNZRHBDL2x0cjh3d1ZLbmZCVHAwTXNuajVIeTV5THRQN2JtRHNnaDcxQm1NdkgKano1QjR3VGx3NysrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://90C0219464A3B76F733B799055F68A0A.sk1.us-east-1.eks.amazonaws.com
  name: cluster-2.us-east-1.eksctl.io
contexts:
- context:
    cluster: cluster-2.us-east-1.eksctl.io
    user: iam-root-account@cluster-2.us-east-1.eksctl.io
  name: iam-root-account@cluster-2.us-east-1.eksctl.io
current-context: iam-root-account@cluster-2.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
- name: iam-root-account@cluster-2.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - cluster-2
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-1
      provideClusterInfo: false
