apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: amit-pod-armor-policy
spec:
  selector:
    matchLabels:
      run: amitpod1
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
  action:
    Block