apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2024-07-23T09:14:54Z"
  name: amit-sa1-bind
  namespace: amitk8s1
  resourceVersion: "2554886"
  uid: 50c61eb6-d412-4008-81ee-b19d5077033e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: amit-pod-readRole
subjects:
- kind: ServiceAccount
  name: amit-sa
  namespace: amitk8s1