apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-splunk
  name: amitsplunklb
  namespace: amit-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: amit-splunk
status:
  loadBalancer: {}
