apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amit-pvc
  namespace: amitk8s1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi