apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-db
  name: amitdblb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: amit-db
status:
  loadBalancer: {}
