apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-deploy
  name: amitlb2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: amit-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
