apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amit-deploy
  name: amit-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amit-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amit-deploy
    spec:
      containers:
      - image: docker.io/amitslj05/kubernetestraining:nginixappv1
        name: kubernetestraining
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50M
            cpu: 50m
          limits:
            memory: 100M
            cpu: 100m
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-deploy
  name: amitlb2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: amit-deploy
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-amit-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: amit.delvex.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amitlb2
            port:
              number: 80
