apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amit-faskapp
  name: amitflasklb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: amit-faskapp
status:
  loadBalancer: {}
